# Generated by Django 4.1.7 on 2023-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='json',
            field=models.FileField(blank=True, upload_to='jsons'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('title', 'type')},
        ),
    ]
