# Generated by Django 4.1.7 on 2023-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesModule', '0002_image_json_alter_image_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='isLabeled',
        ),
        migrations.AddField(
            model_name='image',
            name='workingStatus',
            field=models.CharField(default='Unlabeled', max_length=30),
        ),
    ]
